import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Intro from '../components/Intro'
import Prices from '../components/Prices'
import Testimonial from '../components/Testimonial'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Banner />
     <Intro />
     <Prices />
     <Testimonial />
    </div>
  )
}
